In [5]:
import torch 
import torch.nn as nn
from torch.nn import functional as f
import pandas as pd 
import numpy as np 

In [6]:
data = pd.read_csv("network-logs.csv")

In [7]:
data.describe()

REMOTE_PORT     LATENCY  THROUGHPUT     ANOMALY
count   405.000000  405.000000  405.000000  405.000000
mean     63.555556   14.420702   15.392091    0.029630
std     106.300247    1.449806    1.172879    0.169773
min      20.000000    4.752613    4.126232    0.000000
25%      21.000000   13.408520   15.223188    0.000000
50%      21.000000   15.014320   15.572503    0.000000
75%      80.000000   15.489068   15.868064    0.000000
max     443.000000   23.339868   24.350407    1.000000

In [8]:
data.head()

REMOTE_PORT    LATENCY  THROUGHPUT  ANOMALY
0           21  15.942875   16.202998        0
1           20  12.666451   15.899084        1
2           80  13.894550   12.958008        0
3           21  13.620813   15.459475        0
4           21  15.705485   15.339565        0

In [9]:
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0, test_size=0.2)

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
Xtrain = torch.from_numpy(X_train).float()
Xtest = torch.from_numpy(X_test).float()

In [13]:
Xtrain

tensor([[ 1.1168e-01, -4.7444e-01,  9.7420e-01],
        [-4.1872e-01,  5.9761e-01, -1.2931e+00],
        [-4.2771e-01, -8.5341e-01,  3.6400e-01],
        [-4.1872e-01, -6.1010e-01,  1.6975e-01],
        [-4.2771e-01, -4.7275e-01, -5.1359e-02],
        [-4.1872e-01,  6.6751e-01,  2.7628e-01],
        [ 1.1168e-01,  7.3592e-01,  5.0812e-01],
        [-1.3104e-01,  5.0638e-01, -2.1216e-02],
        [-4.1872e-01,  9.2121e-01,  8.3793e-01],
        [ 1.1168e-01,  6.9220e-01,  7.9390e-01],
        [-4.1872e-01, -3.8346e-01,  2.5869e-01],
        [-4.1872e-01, -1.2169e+00,  1.2829e+00],
        [ 1.1168e-01, -3.1116e-01,  3.5356e-01],
        [-4.1872e-01, -5.1928e-01, -3.0308e+00],
        [-4.0074e-01, -7.9603e-01, -5.7999e-02],
        [ 1.1168e-01, -1.6274e+00, -1.9528e+00],
        [-4.1872e-01,  9.0190e-01,  3.4298e-01],
        [-4.2771e-01,  1.0819e+00,  1.6686e-01],
        [-4.1872e-01, -1.8434e-01,  3.3237e-01],
        [-4.1872e-01, -3.6460e-01,  1.8712e-01],
        [ 1.1168e-01

In [14]:
ytrain = torch.from_numpy(y_train).long()
ytest = torch.from_numpy(y_test).long()

In [15]:
ytrain

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [16]:
Xtrain.shape
ytrain.shape

torch.Size([324])

In [17]:
Xtest.shape
ytest.shape

torch.Size([81])

In [18]:
input_size = 3
output_size = 2
hidden_size = 10

In [19]:
class Net(nn.Module):
    def __init__(self):
         super(Net, self).__init__()
         self.fc1 = torch.nn.Linear(input_size, hidden_size)
         self.fc2 = torch.nn.Linear(hidden_size, hidden_size)
         self.fc3 = torch.nn.Linear(hidden_size, output_size)


    def forward(self, X):
        X = torch.relu((self.fc1(X)))
        X = torch.relu((self.fc2(X)))
        X = self.fc3(X)

        return f.log_softmax(X, dim=1)   

In [20]:
model = Net()

In [21]:
import torch.optim as optim
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
loss_fn = nn.NLLLoss()

In [22]:
epochs = 100

In [23]:
for epoch in range(epochs):
   optimizer.zero_grad()
   ypred = model(Xtrain)
   loss = loss_fn(ypred, ytrain)
   loss.backward()
   optimizer.step()
   print('Epoch', epoch, 'loss', loss.item())

Epoch 0 loss 0.6872124075889587
Epoch 1 loss 0.6469990611076355
Epoch 2 loss 0.6069456934928894
Epoch 3 loss 0.5673146843910217
Epoch 4 loss 0.5284085273742676
Epoch 5 loss 0.4907768964767456
Epoch 6 loss 0.45501944422721863
Epoch 7 loss 0.4213341176509857
Epoch 8 loss 0.3896203339099884
Epoch 9 loss 0.35985201597213745
Epoch 10 loss 0.33199068903923035
Epoch 11 loss 0.30597609281539917
Epoch 12 loss 0.28170815110206604
Epoch 13 loss 0.25903674960136414
Epoch 14 loss 0.2381727397441864
Epoch 15 loss 0.21968205273151398
Epoch 16 loss 0.20348428189754486
Epoch 17 loss 0.18988364934921265
Epoch 18 loss 0.17887364327907562
Epoch 19 loss 0.17009392380714417
Epoch 20 loss 0.16329196095466614
Epoch 21 loss 0.15803678333759308
Epoch 22 loss 0.15403224527835846
Epoch 23 loss 0.1512172371149063
Epoch 24 loss 0.14911796152591705
Epoch 25 loss 0.14740027487277985
Epoch 26 loss 0.1458805948495865
Epoch 27 loss 0.14440736174583435
Epoch 28 loss 0.14294272661209106
Epoch 29 loss 0.14138682186603546
E

In [24]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.7848,  0.0505,  0.0089],
         [ 0.2419, -0.0242, -0.2608],
         [ 0.7150, -0.3129, -0.2668],
         [ 0.0608, -0.0871, -0.3050],
         [-0.4620,  0.4367, -0.3740],
         [ 0.1424, -0.0126, -0.0290],
         [-0.4512, -0.0215, -0.1126],
         [ 0.6148, -0.0559, -0.9826],
         [-0.4073,  0.0768,  0.0050],
         [ 0.2794, -0.0784, -0.1661]], requires_grad=True),
 Parameter containing:
 tensor([-0.1756,  0.5712,  0.0276,  0.9089,  0.0836, -0.2176,  0.7162, -0.8588,
          0.3033,  0.7070], requires_grad=True),
 Parameter containing:
 tensor([[-0.0108, -0.0632,  0.0758, -0.3493,  0.1443,  0.2474, -0.0785,  0.0332,
          -0.2533, -0.2441],
         [ 0.4040,  0.1829, -0.0298,  0.3583,  0.0520,  0.4019,  0.0853, -0.4882,
           0.1037,  0.2947],
         [ 0.3689,  0.0061,  0.1458,  0.5333, -0.1413,  0.0170,  0.4875, -0.5940,
           0.1287,  0.2918],
         [ 0.3635, -0.0961,  0.1850,  0.3391, -0.1350,  0.2337,  0

In [47]:
torch.from_numpy(sc.transform(np.array([[21,15.942875,16.202998]]))).float()


tensor([[-0.4187,  1.1403,  0.7456]])

In [48]:
y_anomaly = model(torch.from_numpy(sc.transform(np.array([[21,15.942875,16.202998]]))).float())

In [49]:
y_anomaly

tensor([[-0.0352, -3.3631]], grad_fn=<LogSoftmaxBackward0>)

In the results if first value is grater than second value there is no anomaly in the network and vice versa.

In [52]:
torch.save(model, 'network_anomaly_detection.pt')

In [53]:
ls

network_anomaly_detection     network-logs.csv
network_anomaly_detection.pt  sample_data/


In [54]:
restored_model = torch.load('network_anomaly_detection.pt')

recommended way of saving model

In [55]:
model.state_dict()

OrderedDict([('fc1.weight', tensor([[ 0.7848,  0.0505,  0.0089],
                      [ 0.2419, -0.0242, -0.2608],
                      [ 0.7150, -0.3129, -0.2668],
                      [ 0.0608, -0.0871, -0.3050],
                      [-0.4620,  0.4367, -0.3740],
                      [ 0.1424, -0.0126, -0.0290],
                      [-0.4512, -0.0215, -0.1126],
                      [ 0.6148, -0.0559, -0.9826],
                      [-0.4073,  0.0768,  0.0050],
                      [ 0.2794, -0.0784, -0.1661]])),
             ('fc1.bias',
              tensor([-0.1756,  0.5712,  0.0276,  0.9089,  0.0836, -0.2176,  0.7162, -0.8588,
                       0.3033,  0.7070])),
             ('fc2.weight',
              tensor([[-0.0108, -0.0632,  0.0758, -0.3493,  0.1443,  0.2474, -0.0785,  0.0332,
                       -0.2533, -0.2441],
                      [ 0.4040,  0.1829, -0.0298,  0.3583,  0.0520,  0.4019,  0.0853, -0.4882,
                        0.1037,  0.2947],
        

In [61]:
torch.save(model.state_dict(), 'network_anomaly_detection_state_dict')

In [62]:
ls

network_anomaly_detection             network-logs.csv
network_anomaly_detection.pt          sample_data/
network_anomaly_detection_state_dict


In [63]:
!zip -r network_anomaly_detection_state_dict.zip network_anomaly_detection_state_dict

  adding: network_anomaly_detection_state_dict (deflated 44%)


In [64]:
ls

network_anomaly_detection             network_anomaly_detection_state_dict.zip
network_anomaly_detection.pt          network-logs.csv
network_anomaly_detection_state_dict  sample_data/


In [65]:
from google.colab import files

In [66]:
files.download('network_anomaly_detection_state_dict.zip')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>